global:
    scrape_interval:     2s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    evaluation_interval: 2s
    external_labels:
        monitor: 'my-monitor'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: project1
    static_configs:
      - targets: [ 'docker.for.mac.localhost:5000' ]